### ISSUE TITLE
Automate sphinx documentation build

### ISSUE THREAD

**Issue by stijnvanhoey** [UGentBiomath/COVID19-Model#36]
@Beramos, as discussed on #35 I would update documentation on each update of the master. The file to put in the `.github/workflows` folder should look more or less like this:

```
name: Upload Python Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[develop]
    - name: Build documentation
      run: |
        python setup.py build_sphinx
    - name: Deploy documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/sphinx/html
```

The main issue is that this won't install the package dependencies defined in `environment.yml`. @jorisvandenbossche -> should we put these requirements in `setup.py`as well (quickly done) or rather adjust the steps above to make it work with conda environment file (overcoming duplicate definition of dependencies)?
